# Netlify build configuration (apps/web)
[build]
  # Turborepo root build executed with pnpm
  base = "."
  command = "pnpm install --frozen-lockfile && pnpm turbo run build --filter @web-sydney/web"
  publish = "apps/web/dist"

# 单页应用（SPA）回退规则：所有路径回退到 index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
