# Netlify build configuration (apps/web)
[build]
  # 在子目录 apps/web 下执行构建
  base = "apps/web"
  # 使用 Turborepo 兼容的 pnpm filter 命令
  command = "pnpm --filter @web-sydney/web build"
  # 发布目录相对 base，为 dist
  publish = "dist"

# 单页应用（SPA）回退规则：所有路径回退到 index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
