const { fileHeader } = require('style-dictionary').formatHelpers;

module.exports = {
  source: ['../../tokens/design-tokens.json'],
  platforms: {
    css: {
      transformGroup: 'css',
      buildPath: '../../vue-frontend/src/generated-tokens/css/',
      files: [{
        destination: 'variables.css',
        format: 'css/variables',
        options: {
          outputReferences: true,
          fileHeader: () => ['Generated by Style Dictionary. Do not edit.'],
        }
      }]
    },
    json: {
      transformGroup: 'js',
      buildPath: '../../vue-frontend/src/generated-tokens/json/',
      files: [{
        destination: 'tokens.json',
        format: 'json/nested'
      }]
    },
    ts: {
      transformGroup: 'js',
      buildPath: '../../vue-frontend/src/generated-tokens/ts/',
      files: [
        {
          destination: 'types.ts',
          format: 'typescript/module-declarations'
        }
      ]
    }
  }
};
