name: Daily Data Update

on:
  schedule:
    # Runs at 11:00, 15:00, and 18:00 AEST (UTC+10)
    # UTC times are 01:00, 05:00, and 08:00
    - cron: '0 1,5,8 * * *'
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run data update script
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python scripts/automated_data_update.py --run-once
